logging:
  level:
    com:
      blog: DEBUG
    org:
      springframework: INFO
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/blog
    username: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

mybatis:
  type-aliases-package: com.blog.entity

mapper:
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
